export const WEBSOCKET_ERRORS = {
  // Authentication errors
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',

  // Request errors
  INVALID_PAYLOAD: 'INVALID_PAYLOAD',
  MISSING_REQUIRED_FIELDS: 'MISSING_REQUIRED_FIELDS',
  INVALID_EVENT_TYPE: 'INVALID_EVENT_TYPE',

  // Handler errors
  HANDLER_NOT_FOUND: 'HANDLER_NOT_FOUND',
  HANDLER_ERROR: 'HANDLER_ERROR',

  // Connection errors
  CONNECTION_LIMIT_EXCEEDED: 'CONNECTION_LIMIT_EXCEEDED',
  DUPLICATE_CONNECTION: 'DUPLICATE_CONNECTION',

  // Room errors
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
  ROOM_ACCESS_DENIED: 'ROOM_ACCESS_DENIED',
  ROOM_CAPACITY_EXCEEDED: 'ROOM_CAPACITY_EXCEEDED',

  // General errors
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
} as const;

export const WEBSOCKET_ERROR_MESSAGES = {
  [WEBSOCKET_ERRORS.UNAUTHORIZED]: 'Authentication required',
  [WEBSOCKET_ERRORS.INVALID_TOKEN]: 'Invalid authentication token',
  [WEBSOCKET_ERRORS.TOKEN_EXPIRED]: 'Authentication token has expired',
  [WEBSOCKET_ERRORS.INVALID_PAYLOAD]: 'Invalid request payload',
  [WEBSOCKET_ERRORS.MISSING_REQUIRED_FIELDS]:
    'Missing required fields in payload',
  [WEBSOCKET_ERRORS.INVALID_EVENT_TYPE]: 'Invalid or unsupported event type',
  [WEBSOCKET_ERRORS.HANDLER_NOT_FOUND]: 'No handler found for this event',
  [WEBSOCKET_ERRORS.HANDLER_ERROR]: 'Error occurred while processing event',
  [WEBSOCKET_ERRORS.CONNECTION_LIMIT_EXCEEDED]:
    'Maximum connection limit exceeded',
  [WEBSOCKET_ERRORS.DUPLICATE_CONNECTION]: 'Duplicate connection detected',
  [WEBSOCKET_ERRORS.ROOM_NOT_FOUND]: 'Room not found',
  [WEBSOCKET_ERRORS.ROOM_ACCESS_DENIED]: 'Access denied to room',
  [WEBSOCKET_ERRORS.ROOM_CAPACITY_EXCEEDED]: 'Room capacity exceeded',
  [WEBSOCKET_ERRORS.INTERNAL_ERROR]: 'Internal server error',
  [WEBSOCKET_ERRORS.SERVICE_UNAVAILABLE]: 'Service temporarily unavailable',
  [WEBSOCKET_ERRORS.RATE_LIMIT_EXCEEDED]: 'Rate limit exceeded',
} as const;

export type WebSocketErrorCode = keyof typeof WEBSOCKET_ERRORS;
