import { WEBSOCKET_EVENTS, WEBSOCKET_ERRORS } from '../constants';

// Extract types from constants
export type WebSocketEventType = typeof WEBSOCKET_EVENTS;
export type WebSocketErrorType = typeof WEBSOCKET_ERRORS;

// Event types
export type CoreWebSocketEvent =
  | typeof WEBSOCKET_EVENTS.CONNECTION
  | typeof WEBSOCKET_EVENTS.DISCONNECT
  | typeof WEBSOCKET_EVENTS.ERROR
  | typeof WEBSOCKET_EVENTS.AUTHENTICATE;

export type NotificationWebSocketEvent =
  | typeof WEBSOCKET_EVENTS.NOTIFICATION.NEW_NOTIFICATION
  | typeof WEBSOCKET_EVENTS.NOTIFICATION.MARK_READ
  | typeof WEBSOCKET_EVENTS.NOTIFICATION.MARK_ALL_READ
  | typeof WEBSOCKET_EVENTS.NOTIFICATION.SUBSCRIBE
  | typeof WEBSOCKET_EVENTS.NOTIFICATION.UNSUBSCRIBE;

export type MessagingWebSocketEvent =
  | typeof WEBSOCKET_EVENTS.MESSAGING.NEW_MESSAGE
  | typeof WEBSOCKET_EVENTS.MESSAGING.TYPING_START
  | typeof WEBSOCKET_EVENTS.MESSAGING.TYPING_STOP
  | typeof WEBSOCKET_EVENTS.MESSAGING.MESSAGE_READ
  | typeof WEBSOCKET_EVENTS.MESSAGING.MESSAGE_DELIVERED
  | typeof WEBSOCKET_EVENTS.MESSAGING.JOIN_CONVERSATION
  | typeof WEBSOCKET_EVENTS.MESSAGING.LEAVE_CONVERSATION
  | typeof WEBSOCKET_EVENTS.MESSAGING.CONVERSATION_UPDATED;

export type PostsWebSocketEvent =
  | typeof WEBSOCKET_EVENTS.POSTS.SUBSCRIBE_POST
  | typeof WEBSOCKET_EVENTS.POSTS.UNSUBSCRIBE_POST
  | typeof WEBSOCKET_EVENTS.POSTS.SUBSCRIBE_FEED
  | typeof WEBSOCKET_EVENTS.POSTS.UNSUBSCRIBE_FEED
  | typeof WEBSOCKET_EVENTS.POSTS.NEW_POST
  | typeof WEBSOCKET_EVENTS.POSTS.POST_UPDATED
  | typeof WEBSOCKET_EVENTS.POSTS.POST_DELETED
  | typeof WEBSOCKET_EVENTS.POSTS.REACT_POST
  | typeof WEBSOCKET_EVENTS.POSTS.UNREACT_POST
  | typeof WEBSOCKET_EVENTS.POSTS.POST_REACTION_UPDATE
  | typeof WEBSOCKET_EVENTS.POSTS.ADD_COMMENT
  | typeof WEBSOCKET_EVENTS.POSTS.UPDATE_COMMENT
  | typeof WEBSOCKET_EVENTS.POSTS.DELETE_COMMENT
  | typeof WEBSOCKET_EVENTS.POSTS.NEW_COMMENT
  | typeof WEBSOCKET_EVENTS.POSTS.COMMENT_UPDATED
  | typeof WEBSOCKET_EVENTS.POSTS.COMMENT_DELETED
  | typeof WEBSOCKET_EVENTS.POSTS.FEED_UPDATE
  | typeof WEBSOCKET_EVENTS.POSTS.POST_ANALYTICS;

export type AnyWebSocketEvent =
  | CoreWebSocketEvent
  | NotificationWebSocketEvent
  | MessagingWebSocketEvent
  | PostsWebSocketEvent;
