import { Injectable, Inject } from '@nestjs/common';
import { AuthSession } from '../entities/session.entity';
import { Token } from '../value-objects/token.vo';
import { ISessionRepository } from '../repositories/session.repository';

/**
 * Session Domain Service
 * Contains business logic for session management
 */
@Injectable()
export class SessionDomainService {
  constructor(
    @Inject('SESSION_REPOSITORY')
    private readonly sessionRepository: ISessionRepository,
  ) {}

  /**
   * Create session with business rules validation
   */
  async createSession(
    userId: string,
    refreshToken: string,
    expiresAt: Date,
    ipAddress?: string,
    userAgent?: string,
  ): Promise<AuthSession> {
    // Business rule: Check max sessions per user
    const existingSessions = await this.sessionRepository.findByUserId(userId);
    const maxSessionsPerUser = 5;

    if (existingSessions.length >= maxSessionsPerUser) {
      // Remove oldest session
      const oldestSession = existingSessions.sort(
        (a, b) => a.createdAt.getTime() - b.createdAt.getTime(),
      )[0];
      await this.sessionRepository.delete(oldestSession.id);
    }

    // Create new session
    const session = AuthSession.create({
      id: '', // Will be generated by repository
      userId,
      refreshToken: new Token(refreshToken),
      expiresAt,
      ipAddress,
      userAgent,
    });

    return await this.sessionRepository.create(session);
  }

  /**
   * Validate session business rules
   */
  async validateSession(sessionId: string): Promise<boolean> {
    const session = await this.sessionRepository.findBySessionId(sessionId);

    if (!session) {
      return false;
    }

    return session.isValid();
  }

  /**
   * Revoke session with business validation
   */
  async revokeSession(sessionId: string): Promise<void> {
    const session = await this.sessionRepository.findBySessionId(sessionId);

    if (!session) {
      throw new Error('Session not found');
    }

    if (session.isRevoked) {
      throw new Error('Session already revoked');
    }

    const revokedSession = session.revoke();
    await this.sessionRepository.update(session.id, revokedSession);
  }
}
