version: '3.8'

services:
  api:
    build: .
    container_name: socialmedia_api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - '3107:3107'
