version: '3.8'

services:
  api:
    build: .
    container_name: socialmedia_api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - REDIS_URL_WORKER=${REDIS_URL_WORKER}
    ports:
      - '3107:3107'
    networks:
      - smnet

  worker:
    build: .
    container_name: socialmedia_worker
    restart: unless-stopped
    command: node dist/workers/main.js
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - REDIS_URL_WORKER=${REDIS_URL_WORKER}
    networks:
      - smnet

networks:
  smnet:
    driver: bridge
