/**
 * Dependency Injection Tokens for Reactions Module
 */

// Repository Token
export const REACTION_REPOSITORY_TOKEN = 'REACTION_REPOSITORY';

// External Service Tokens
export const EXTERNAL_POST_SERVICE_TOKEN = 'EXTERNAL_POST_SERVICE';
export const EXTERNAL_COMMENT_SERVICE_TOKEN = 'EXTERNAL_COMMENT_SERVICE';
export const EXTERNAL_USER_SERVICE_TOKEN = 'EXTERNAL_USER_SERVICE';
export const NOTIFICATION_SERVICE_TOKEN = 'NOTIFICATION_SERVICE';
